const GET_ARTICLES = "GET_ARTICLES"
const SET_ARTICLES = "SET_ARTICLES"
const SET_ARTICLE_PAGENUM = "SET_ARTICLE_PAGENUM"
const GET_ARTICLE_PAGENUM = 'GET_ARTICLE_PAGENUM'
const SET_ARTICLE_SIZE = "SET_ARTICLE_SIZE"
const GET_ARTICLE_SIZE = 'GET_ARTICLE_SIZE'
const SET_ARTICLE_RECORDS = "SET_ARTICLE_RECORDS"
const SET_ARTICLE_INFO = "SET_ARTICLE_INFO"

export default {
  GET_ARTICLES,
  SET_ARTICLES,
  GET_ARTICLE_PAGENUM,
  GET_ARTICLE_SIZE,
  SET_ARTICLE_PAGENUM,
  SET_ARTICLE_SIZE,
  SET_ARTICLE_RECORDS,
  SET_ARTICLE_INFO
}
