const GET_ARTICLES = "GET_ARTICLES"                 //获取文章列表
const SET_ARTICLES = "SET_ARTICLES"                 //设置文章列表
const GET_ARTICLE_DETAIL = "GET_ARTICLE_DETAIL"     //获取文章详情
const SET_ARTICLE_DETAIL = "SET_ARTICLE_DETAIL"     //设置文章详情

const GET_COMMENT = "GET_COMMENT"     //获取文章详情
const SET_COMMENT = "SET_COMMENT"     //设置文章详情

const GET_USER = "GET_USER"
const SET_USER = "SET_USER"

const GET_SITE_SETTINGS = "GET_SITE_SETTINGS"
const SET_SITE_SETTINGS = "SET_SITE_SETTINGS"


const SET_ARTICLE_PAGENUM = "SET_ARTICLE_PAGENUM"
const GET_ARTICLE_PAGENUM = 'GET_ARTICLE_PAGENUM'
const SET_ARTICLE_SIZE = "SET_ARTICLE_SIZE"
const GET_ARTICLE_SIZE = 'GET_ARTICLE_SIZE'
const SET_ARTICLE_RECORDS = "SET_ARTICLE_RECORDS"
const SET_ARTICLE_INFO = "SET_ARTICLE_INFO"

const GET_SITE_HEADER = 'GET_SITE_HEADER'
const SET_SITE_HEADER = 'SET_SITE_HEADER'
const GET_SITE_FOOTER = 'GET_SITE_FOOTER'
const SET_SITE_FOOTER = 'SET SITE_FOOTER'

export default {
  GET_ARTICLES,
  SET_ARTICLES,
  GET_ARTICLE_DETAIL,
  SET_ARTICLE_DETAIL,
  GET_COMMENT,
  SET_COMMENT,
  GET_USER,
  SET_USER,
  GET_SITE_SETTINGS,
  SET_SITE_SETTINGS,

  GET_ARTICLE_PAGENUM,
  GET_ARTICLE_SIZE,
  SET_ARTICLE_PAGENUM,
  SET_ARTICLE_SIZE,
  SET_ARTICLE_RECORDS,
  SET_ARTICLE_INFO,
  GET_SITE_FOOTER,
  GET_SITE_HEADER,
  SET_SITE_FOOTER,
  SET_SITE_HEADER
}
